### ISSUE TITLE
extra with

### ISSUE THREAD

**Issue by ConrDev** [nietrenswens/levend-monopoly#2]
https://github.com/nietrenswens/levend-monopoly/blob/dd01463352fa816780d5087302812c950f996c73/app/Http/Controllers/ManagementController.php#L20

Can be one compact
```php
view('overview')->with(compact('gebouwen', 'users'));
```

**Comment by nietrenswens** [comment]
Thanks, will get to it.

**Comment by nietrenswens** [comment]
Issue has been resolved in the latest commit.
